### ISSUE TITLE
朋友圈同名用户的辨别。一模一样的用户名，头像也不具备分辨度，有时会评论给错的人。

### ISSUE THREAD

**Issue by PlutoZhang** [PlutoZhang/patent_2018#5]
4. 朋友圈同名用户的辨别。一模一样的用户名，头像也不具备分辨度，有时会评论给错的人。

**Comment by PlutoZhang** [comment]
微信，头像，昵称频繁变换，如何分辨？

**Comment by niuya** [comment]
Solution: 分析近期与该用户的聊天记录，提取关键词，以tag形式显示在用户名旁边。需要考虑用户数据隐私保护的问题。
