### ISSUE TITLE
对于买回来的物品过期提醒

### ISSUE THREAD

**Issue by zManage** [PlutoZhang/patent_2018#7]
有时候买回来的东西多了，很难记清楚它们的生产日期以及过期的日期。如果单纯靠人脑记忆，容易遗忘也容易搞混。如果手动记录又太麻烦。有没有一种比较方便的方式，比如手机的APP，可以扫描买回物品上面的二维码或者其他标识码，记录他们的生产日期及过期日期，在距离过期日期某段时间的时候给予提醒。以免等物品过期了还不知晓，造成物品的浪费。:-)

**Comment by PlutoZhang** [comment]
看了下市面上有几款这样的app，但都是很笨地需要用户手动输入物件名字和到期时间。我们可以想想如何更方便录入这些信息并进行管理。
类似app:
https://sspai.com/post/23391
https://sspai.com/post/32695

**Comment by PlutoZhang** [comment]
也是建议close...沃尔玛等大型商超肯定有了解决方案。我们用的技术可能已经被涵盖。换个角度，站在IBM的位置，再想想。
